require "base64"

default_platform(:ios)

platform :ios do
  lane :beta do

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: Base64.decode64(ENV["APP_STORE_CONNECT_KEY_CONTENT"]),
      is_key_content_base64: true
    )

    team = ENV["APPLE_TEAM_ID"]
    UI.user_error!("Missing APPLE_TEAM_ID") if team.to_s.strip.empty?

    build_app(
      scheme: "EchoAir",
      export_method: "app-store",
      export_team_id: team,
      xcargs: "DEVELOPMENT_TEAM=#{team} -allowProvisioningUpdates"
    )

    upload_to_testflight(
      api_key: api_key
    )
  end
end