lane :beta do
  team = ENV["APPLE_TEAM_ID"]

  UI.user_error!("Missing APPLE_TEAM_ID") if team.to_s.strip.empty?

  build_app(
    scheme: "EchoAir",
    export_method: "app-store",
    export_team_id: team,
    xcargs: "DEVELOPMENT_TEAM=#{team}"
  )

  upload_to_testflight
end