name: iOS Build & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install XcodeGen
        run: |
          brew update
          brew install xcodegen
          xcodegen --version

      - name: Generate Xcode project
        run: xcodegen generate

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      - name: Install Fastlane
        run: gem install fastlane

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install Pods
        run: pod install || true

      - name: Build & Upload
        env:
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_KEY_CONTENT }}
        run: fastlane beta